[workspace]
resolver = "3"
members = ["backend", "backend/migration", "backend/entity"]

[workspace.dependencies]
serde = { version = "1.0.223", features = ["derive"] }
sea-orm = { version = "1.1.16", features = [
  "sqlx-sqlite",
  "runtime-tokio-rustls",
] }
