[package]
name = "ichwilldich-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
rust-derive = { path = "../rust-derive" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
clap = { workspace = true }
axum = { workspace = true }
axum-extra = { workspace = true }
http = { workspace = true }
tower-http = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde-xml-rs = { workspace = true }
hmac = { workspace = true }
chrono = { workspace = true }
eyre = { workspace = true }
color-eyre = { workspace = true }
jsonwebtoken = { workspace = true }
tracing-error = "0.2.1"

[lib]
path = "src/lib.rs"
