name: Linting and Formatting
on:
  pull_request:

jobs:
  linters:
    name: Run linters
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
      - uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo and rust files
        id: rust_cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          shared-key: "linter_cache"
      - uses: bahmutov/npm-install@v1

      - name: Run linters
        uses: profiidev/rust-lint-action@v3
        with:
          rustfmt: true
          clippy: true
          auto_fix: true
          prettier: true
          prettier_extensions: "css,html,js,json,jsx,md,sass,scss,ts,tsx,vue,yaml,yml,svelte"
          svelte: true
          svelte_args: "--ignore target --no-tsconfig"
          tsc: true
