name: Checks and Validation
on:
  pull_request:

jobs:
  linters:
    name: Run linters
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.RELEASE_PLZ_TOKEN }}

      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Generate svelte data
        run: |
          npm run sync

      - name: Run linters
        uses: profiidev/rust-lint-action@v3
        with:
          auto_fix: true
          prettier: true
          prettier_extensions: 'css,html,js,json,jsx,md,sass,scss,ts,tsx,vue,yaml,yml,svelte'
          svelte: true
