name: Components Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1" # Every Monday at midnight UTC

jobs:
  update-components:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - uses: bahmutov/npm-install@v1

      - name: Update components
        run: |
          cd packages/svelte
          npx -y shadcn-svelte@latest update -ay
          grep -rl '@lib' . | xargs sed -i 's/$lib/@lib/g'
          git restore package.json
          npx -y prettier -cw .
          cd ../..
          git restore package-lock.json

      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          commit-message: "chore: updated components"
          branch: "chore/update-components-${{ github.run_id }}"
          title: "chore: update components"
          body: "This PR updates the components to the latest versions."
          base: main
          sign-commits: true
          labels: components-update
